### ISSUE TITLE
Example DockerCompose file

### ISSUE THREAD

**Issue by meichthys** [officelifehq/docker#11]
Great work!
An example docker-compose.yml file would be helpful for self-hosted deployments.

**Comment by crishnakh** [comment]
Almost a year... any news?

**Comment by meichthys** [comment]
This is enough to play around:
⚠ Note: don't try to put this behind a reverse proxy with https, it will probably fail with a mixed content warning in browser consoles.
```
version: '3.3'
services:
    officelifehq:
        container_name: officelife
        ports:
            - '<your_host_port_here>:80'
        volumes:
            - '/var/run/docker.sock:/tmp/docker.sock:ro'
        restart: always
        logging:
            options:
                max-size: 1g
        image: 'ghcr.io/officelifehq/officelife-dev:main-apache'
```
